### ISSUE TITLE
I know it was tricky to learn how to do a mosaic plot, so kudos! However, I honestly am very confused by the code and would have appreciated more annotation for how to code and interpret the plot!

### ISSUE THREAD

**Issue by VAbramc** [Bucknell-Biol364/Project_1_Group_5_2024#9]
https://github.com/Bucknell-Biol364/Project_1_Group_5_2024/blob/5b3453968145127e28ebf30a105a12ea5a94e3ca/Project01.md?plain=1#L605

**Comment by shihabnihan** [comment]
I honestly am not 100% sure about mosaic plots because this is the first time I am seeing one. The code that we have for that was not made by us and is instead supplied by R. 
But I will do my best to explain each line the best I can by looking it up on google.
